---
version: "2"
services:
  expressvpn:
    container_name: expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE=${VPN_CODE}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      - 8112:8112 # ports of other containers that use the vpn (to access them locally)
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: service:expressvpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
    depends_on:
      - expressvpn
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env # Timezone
      - PUID=${PUID} # default user id, defined in .env # User ID to run as
      - PGID=${PGID} # default group id, defined in .env # Group ID to run as
    volumes:
      - ${ROOT}/data:/data # Location of all your media
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989/tcp # Web UI
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and directories created by Radarr
      - TZ=${TZ} # timezone, defined in .env # Timezone
      - PUID=${PUID} # default user id, defined in .env # User ID to run as
      - PGID=${PGID} # default group id, defined in .env # Group ID to run as
    volumes:
      - ${ROOT}/data:/data # Location of all your media
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878/tcp # The port for the Radarr webinterface

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - UMASK_SET # Control permissions of files and directories created by Bazarr
      - TZ=${TZ} # timezone, defined in .env # Timezone
      - PUID=${PUID} # default user id, defined in .env # User ID to run as
      - PGID=${PGID} # default group id, defined in .env # Group ID to run as
    volumes:
      - ${ROOT}/data:/data # Location of all your media
      - ${ROOT}/config/bazarr:/config # config files
    ports:
      - 6767:6767/tcp # Allows HTTP access to the internal webserver.
  prowlarr:
    image: linuxserver/prowlarr:nightly-version-0.1.0.624
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/prowlarr:/config
    ports:
      - 9696:9696
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/ombi:/config
    ports:
      - 3579:3579
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/tautulli:/config
    ports:
      - 8181:8181
